#pragma once

#define BFX_USBHOST_BASE_MODULE_ID (CY_RSLT_MODULE_USER_BASE + 0x01)
#define BFX_USBHOST_TASK_CREATE_FAILED CY_RSLT_CREATE(CY_RSLT_TYPE_ERROR, BFX_USBHOST_BASE_MODULE_ID, 0x01)
#define BFX_USBHOST_CANNOT_OPEN_HID_DEVICE CY_RSLT_CREATE(CY_RSLT_TYPE_ERROR, BFX_USBHOST_BASE_MODULE_ID, 0x02)
#define BFX_USBHOST_TOO_MANY_HID_DEVICES CY_RSLT_CREATE(CY_RSLT_TYPE_ERROR, BFX_USBHOST_BASE_MODULE_ID, 0x03)